language: zh_CN
nameTag: '&r {mob.name} &cLv.&e{level.level}'
bossbar:
  __class__: cat.nyaa.infiniteinfernal.configs.BossbarConfig
  enabled: true
  killsuffix: ' &e[ &4x &e]'
tags:
- im_mob
addEffects:
  disorder: effect:CONFUSION:10
  dementia: effect:SLOW_DIGGING:10
  target_lost: effect:BLINDNESS:10
worlds:
  Rysnoaks:
    __class__: cat.nyaa.infiniteinfernal.configs.WorldConfig
    enabled: true
    disable-natural-spawning: true
    max-mob-per-player: 5
    max-mob-in-world: 160
    spawn-range-min: 10
    spawn-range-max: 24
    spawn-interval: 20
    mob-active-interval: 60
    aggro:
      __class__: cat.nyaa.infiniteinfernal.configs.WorldConfig$AggroConfig
      range:
        __class__: cat.nyaa.infiniteinfernal.configs.WorldConfig$AggroConfig$RangeConfig
        min: 4
        max: 64
      base: 28
      dec: effect:INVISIBILITY:10
      inc: effect:GLOWING:10
    looting:
      __class__: cat.nyaa.infiniteinfernal.configs.WorldConfig$LootingConfig
      global: 100
      overall:
        __class__: cat.nyaa.infiniteinfernal.configs.WorldConfig$LootingConfig$LootingModifiers
        inc: []
        dec: []
        max: 100.0
      dynamic:
        __class__: cat.nyaa.infiniteinfernal.configs.WorldConfig$LootingConfig$LootingModifiers
        inc: []
        dec: []
        max: 100.0
    friendlyfire:
      __class__: cat.nyaa.infiniteinfernal.configs.WorldConfig$FriendlyFireConfig
      enable: false
      effect: UNLUCK:9:600
    broadcast:
      __class__: cat.nyaa.infiniteinfernal.configs.WorldConfig$BroadcastConfig
      default: NEARBY
      range: 64
    enableTrueDamage: true
    trueDamage:
      wither: 0.0
      poison: 0.0
      fire_tick: 0.0
      fire: 0.0
      lava: 10.0
      lightning: 1.0
      magic: -1.01
      suffocation: 1.0
      void: 4.0
      drowning: 2.0
      hot_floor: 0.0
      starvation: 0.0
      dragon_breath: 0.0
      contact: 0.0
    spawn:
      light:
        sky:
          min: 0
          max: 15
        block:
          min: 0
          max: 15
        total:
          min: 1
          max: 15
    despawnRange: 128.0
GetDropMessageFeedback: false
groupShareRange: 50
enableActionbarInfo: false
groupCapacity: 8
player:
  base:
    mana: 20.0
    rage: 100.0
enabled: true
dps:
  title: '&aDPS: &c{dps} &atotal: &c{total} &amax: &c{max}'
  default:
    health: 2048.0
  refresh_interval: 200
  entity_tag: ''
mobParticle:
  __class__: cat.nyaa.infiniteinfernal.configs.ParticleConfig
  type: SOUL_FIRE_FLAME
  deltaX: 0.5
  deltaY: 0.1
  deltaZ: 0.5
  speed: 0.0
  amount: 10
  forced: false
